Web/Areas/Admin/Controllers/BasicParamsController.cs
using CRM_System.BLL;
using CRM_System.Model;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Base;

namespace Web.Areas.Admin.Controllers
{
    public class BasicParamsController : BaseAdminController
    {

        // GET: /Admin/BasicParams/
        Mpr_Basic_ParamsService  BasicParamsService = new Mpr_Basic_ParamsService();
        public ActionResult Index(int? page, string Keyword = "",int BasicType = -1)
        {
            int currid = Convert.ToInt32(currentadminUser.ID);
            int pageIndex = page ?? 1;
            int pageSize = 10;
            int totalCount = 0;
            if (BasicType == -1)
            {
                List<Mpr_Basic_Params> Pglist = BasicParamsService.GetPage(s => s.ParamsName.Contains(Keyword), s => s.Addtime, pageIndex, 10,ref totalCount);
                var ResultList = new StaticPagedList<Mpr_Basic_Params>(Pglist, pageIndex, pageSize, totalCount);
                return View(ResultList);
            }
            else
            {
                List<Mpr_Basic_Params> Pglist = BasicParamsService.GetPage(s => s.ParamsName.Contains(Keyword) && s.BasicType == BasicType, s => s.Addtime, pageIndex, 10, ref totalCount);
                var ResultList = new StaticPagedList<Mpr_Basic_Params>(Pglist,pageIndex , pageSize, totalCount);
                return View(ResultList);
            }
        }

        public ActionResult Edit(string id)
        {
            Mpr_Basic_Params ParamsMod = BasicParamsService.GetModel(s => s.ID == id);
            if (ParamsMod == null)
            {
                ParamsMod = new Mpr_Basic_Params();
            }
            return View(ParamsMod);
        }


        [ValidateInput(false)]
        [HttpPost]
        public string Save(string ID, int BasicType, string ParamsName)
        {
            ReturnJson Result = new ReturnJson();
            try
            {
                Mpr_Basic_Params TypeMod = BasicParamsService.GetModel(s => s.ID == ID);
                if (TypeMod == null)
                {
                    TypeMod = new Mpr_Basic_Params();
                    TypeMod.ID = Guid.NewGuid().ToString("N");
                    TypeMod.BasicType = BasicType;
                    TypeMod.ParamsName = ParamsName;
                    TypeMod.Addtime = DateTime.Now;
                    TypeMod.Adduser = currentadminUser.ID;
                    BasicParamsService.Insert(TypeMod);
                }
                else
                {
                    TypeMod.BasicType = BasicType;
                    TypeMod.ParamsName = ParamsName;
                    BasicParamsService.Update(TypeMod);
                }
                Result.Code = "0";
                Result.Errmsg = "保存成功";
            }
            catch (Exception ex)
            {
                Result.Code = "1";
                Result.Errmsg = "保存异常";
            }
            return ToJson(Result);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public string DelRow(string RowID)
        {
            ReturnJson Result = new ReturnJson();
            int DelRow = BasicParamsService.DelBy(s => s.ID == RowID);
            if (DelRow > 0)
            {
                Result.Code = "0";
                Result.Errmsg = "删除成功";
            }
            else
            {
                Result.Code = "1";
                Result.Errmsg = "删除失败";
            }
            return ToJson(Result);
        }
    }
}

Web/Areas/Admin/Views/BasicParams/Edit.cshtml
@model CRM_System.Model.Mpr_Basic_Params
@{
    ViewBag.Title = "基础信息维护";
}
<script src="~/Areas/Admin/Script/BasicParams/Edit.js?@(new Random().Next(10000))"></script>
<div class="col-md-12" style="margin-top:15px;">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title" title="">基础信息维护</h3>
        </div>
        <div class="box-body" style="padding-top:10px;">
            <div class="form-group">
                <label for="exampleInputEmail1" title="参数类型">参数类型:</label>
                <select id="BasicType" name="BasicType" class="form-control" style="width:30%;">
                      @foreach (int item in Enum.GetValues(typeof(CRM_System.BLL.BasicType)))
                      {
                          if (Model.BasicType == item)
                          {
                            <option value="@(item)" selected="selected">@((CRM_System.BLL.BasicType)item)</option>
                          }
                          else
                          {
                            <option value="@(item)">@((CRM_System.BLL.BasicType)item)</option>
                          }
                      }
                </select>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1" title="参数内容">参数内容:</label>
                <input type="text" class="form-control" style="width:50%;" id="ParamsName" name="ParamsName" placeholder="Enter..." value="@(Model.ParamsName)" />
            </div>
        </div>
        <div class="box-footer">
            <input type="hidden" id="ID" name="ID" value="@(Model.ID)" />
            <button type="button" class="btn btn-primary" id="EditBtn">保存</button>
        </div>
    </div>
</div>

Web/Areas/Admin/Views/BasicParams/Index.cshtml
@model PagedList.IPagedList<CRM_System.Model.Mpr_Basic_Params>
@using PagedList.Mvc;
@{
    ViewBag.Title ="基础选项维护";
}
<!-- Content Header (Page header) -->
<script src="~/Areas/Admin/Script/BasicParams/Index.js?@(new Random().Next(1011))"></script>


<div id="page" class="con_right">
    <div class="con_right0">
        <div class="con_right1 pull-left">
            <span class="pull-left"><img src="/Content/CRM_System/images/ico1.jpg"></span>
            <h3 class="pull-left">基础选项维护</h3>
        </div>
        <div class="con_right2 pull-right">
            <ol class="breadcrumb">
                <li><a href="javascript:parent.location.href='/'">Home</a></li>
                <li><a href="javascript:void(0);">基础参数维护</a></li>
                <li class="active"><a href="/admin/BasicParams">基础参数维护</a></li>
            </ol>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="ser">
        <div class="form-inline">

            @using (Html.BeginForm("Index", "BasicParams", FormMethod.Get))
            {
                <div class="input-group">
                    <input type="text" class="form-control input-sm" style="width: 150px;" placeholder="分类名称" name="Keyword" id="Keyword" />
                    <button type="submit" class="btn btn-default" id="Serchbtn" name="roleser" style="margin-left:15px;" value="搜索">搜索</button>
                    <button type="button" class="btn btn-default" id="roleadd" name="roleadd" style="margin-left:15px;" value="添加">添加</button>
                </div>
            }


        </div>
    </div>

    <div class="con_right3">
        <table class="table table-hover table-bordered table-responsive" id="table">
            <thead>
                <tr class="info first">
                    <th style="text-align:center; vertical-align:middle;" title="操作">操作</th>
                    <th style="text-align:center; vertical-align:middle;" title="类型">类型</th>
                    <th style="text-align:center; vertical-align:middle;" title="内容">内容</th>
                    <th style="text-align:center; vertical-align:middle;" title="添加时间">添加时间</th>
                </tr>
            </thead>
            <tbody style="text-align: center" id="GetBody">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a href="javascript:void(0);" name="roleedit" clt="@(item.ID)"><span class="glyphicon glyphicon-edit">编辑</span></a>
                            <a href="javascript:void(0);" name="roledel" clt="@(item.ID)"><span class="glyphicon glyphicon-trash">删除</span></a>
                        </td>
                        <td>@((CRM_System.BLL.BasicType)item.BasicType)</td>
                        <td>@(item.ParamsName)</td>
                        <td>@(item.Addtime)</td> 
                    </tr>
                }
            </tbody>
        </table>
    </div> 
    <!--分页开始--> 
    <div class="OptionPagerList" style="text-align:center;">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
</div>