Web/Areas/Admin/Controllers/MaterialTypeController.cs
using CRM_System.BLL;
using CRM_System.Model;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Base;

namespace Web.Areas.Admin.Controllers
{
    public class MaterialTypeController : BaseAdminController
    {
        //
        // GET: /Admin/MaterialType/ 
        Mpr_Material_TypeService Material_TypeService = new Mpr_Material_TypeService(); 
        public ActionResult Index(int? page, string Keyword = "")
        {
            int currid = Convert.ToInt32(currentadminUser.ID);
            int pageIndex = page ?? 1;
            int pageSize = 10;
            int totalCount = 0;
            List<Mpr_Material_Type> Pglist = Material_TypeService.GetPage(s => s.TypeName.Contains(Keyword), s => s.Sort, pageIndex, 10, ref totalCount);
            var ResultList = new StaticPagedList<Mpr_Material_Type>(Pglist, pageIndex, pageSize, totalCount);
            return View(ResultList);
        }

        public ActionResult Edit(string id)
        {
            Mpr_Material_Type Matermod = Material_TypeService.GetModel(s => s.ID == id);
            if (Matermod == null)
            {
                Matermod = new Mpr_Material_Type();
            }
            return View(Matermod);
        }

        [ValidateInput(false)]
        [HttpPost]
        public string Save(string ID, string TypeName, int Sort)
        {
            ReturnJson Result = new ReturnJson();
            try
            {
                Mpr_Material_Type TypeMod = Material_TypeService.GetModel(s => s.ID == ID);
                if (TypeMod == null)
                {
                    TypeMod = new Mpr_Material_Type();
                    TypeMod.ID = Guid.NewGuid().ToString("N");
                    TypeMod.TypeName = TypeName;
                    TypeMod.Sort = Sort;
                    TypeMod.AddTime = DateTime.Now;
                    TypeMod.AddUser = currentadminUser.ID;
                    Material_TypeService.Insert(TypeMod);
                }
                else
                {
                    TypeMod.TypeName = TypeName;
                    TypeMod.Sort = Sort;
                    TypeMod.UpdateTime = DateTime.Now;
                    TypeMod.UpdateUser = currentadminUser.ID;
                    Material_TypeService.Update(TypeMod);
                }
                Result.Code = "0";
                Result.Errmsg = "保存成功";
            }
            catch (Exception ex)
            {
                Result.Code = "1";
                Result.Errmsg = "保存异常";
            }
            return ToJson(Result);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public string DelRow(string RowID)
        {
            ReturnJson Result = new ReturnJson();
            int DelRow = Material_TypeService.DelBy(s => s.ID == RowID);
            if (DelRow > 0)
            {
                Result.Code = "0";
                Result.Errmsg = "删除成功";
            }
            else {
                Result.Code = "1";
                Result.Errmsg = "删除失败";
            }
            return ToJson(Result);
        }
    }
}

Web/Areas/Admin/Views/MaterialType/Edit.cshtml
@model CRM_System.Model.Mpr_Material_Type
@{
    ViewBag.Title = "素材库参数";
}
<script src="~/Areas/Admin/Script/MaterialType/Edit.js?@(new Random().Next(10000))"></script>
<div class="col-md-12" style="margin-top:15px;">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title" title="">素材库参数</h3>
        </div>
        <div class="box-body" style="padding-top:10px;">
            <div class="form-group">
                <label for="exampleInputEmail1" title="类型名称">类型名称:</label>
                <input type="text" class="form-control" style="width:50%;" id="TypeName" name="TypeName" placeholder="Enter..."  value="@(Model.TypeName)" />
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1" title="排序编号">排序编号:</label>
                <input type="number" class="form-control" style="width:50%;" id="Sort" name="Sort" placeholder="Enter..." value="@(Model.Sort)"  />
            </div>
        </div>
        <div class="box-footer">
            <input type="hidden" id="ID" name="ID" value="@(Model.ID)" />
            <button type="button" class="btn btn-primary" id="EditBtn">保存</button>
        </div>
    </div>
</div>

Web/Areas/Admin/Views/MaterialType/Index.cshtml
@model PagedList.IPagedList<CRM_System.Model.Mpr_Material_Type>
@using PagedList.Mvc;
@{
    ViewBag.Title = "素材类型维护";
}
<!-- Content Header (Page header) -->
<script src="~/Areas/Admin/Script/MaterialType/Index.js?@(new Random().Next(1011))"></script>


<div id="page" class="con_right">
    <div class="con_right0">
        <div class="con_right1 pull-left">
            <span class="pull-left"><img src="/Content/CRM_System/images/ico1.jpg"></span>
            <h3 class="pull-left">素材类型维护</h3>
        </div>
        <div class="con_right2 pull-right">
            <ol class="breadcrumb">
                <li><a href="javascript:parent.location.href='/'">Home</a></li>
                <li><a href="javascript:void(0);">素材库</a></li>
                <li class="active"><a href="/admin/MaterialType">素材类型维护</a></li>
            </ol>
        </div>
        <div class="clearfix"></div>
    </div>
     
    <div class="ser">
        <div class="form-inline">

            @using (Html.BeginForm("Index", "MaterialType", FormMethod.Get))
            {
                <div class="input-group">
                    <input type="text" class="form-control input-sm" style="width: 150px;" placeholder="分类名称" name="Keyword" id="Keyword" />
                    <button type="submit" class="btn btn-default" id="Serchbtn" name="roleser" style="margin-left:15px;" value="搜索">搜索</button>
                    <button type="button" class="btn btn-default" id="roleadd" name="roleadd" style="margin-left:15px;" value="添加">添加</button>
                </div>
            }


        </div>
    </div>

    <div class="con_right3">
        <table class="table table-hover table-bordered table-responsive" id="table">
            <thead>
                <tr class="info first">
                    <th style="text-align:center; vertical-align:middle;" title="操作">操作</th>
                    <th style="text-align:center; vertical-align:middle;" title="名称">名称</th>
                    <th style="text-align:center; vertical-align:middle;" title="排序编号">排序编号</th>
                    <th style="text-align:center; vertical-align:middle;" title="添加时间">添加时间</th>
                </tr>
            </thead>
            <tbody style="text-align: center" id="GetBody">
                @foreach (var item in Model)
                {
                    <tr>
                        <td><a href="javascript:void(0);" name="roleedit" clt="@(item.ID)"><span class="glyphicon glyphicon-edit">编辑</span></a>
                            <a href="javascript:void(0);" name="roledel" clt="@(item.ID)"><span class="glyphicon glyphicon-trash">删除</span></a>
                        </td>
                        <td>@(item.TypeName)</td> 
                        <td>@(item.Sort)</td> 
                        <td>@(item.AddTime)</td> 
                   
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <!--分页开始-->

    <div class="OptionPagerList" style="text-align:center;">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
</div>